name: Build-Docker-Image 
on:
  push: 
    branches: [ main ]
  pull_request: 
    branches: [ main ]
  jobs: 
    runs-on: ubuntu-latest 
    env: 
      TAG: dockerIMG-test 
      PAT: ${{ secrets.GITHUB_TOKEN }} 
      USER: manucu2k
      REGISTRY: ghcr.io
      VERSION: V1

    steps: 
      - name: Checkout 
        uses: actions/checkout@v3 

      - name: Build Docker Image 
        run: docker build -t $TAG . 

      - name: Login to GHCR
        run:  |
          echo $PAT | docker login ghcr.io -u $USER —password-stdin 
          docker tag $TAG ${{ env.REGISTRY }}/$USER/$TAG:${{ env.VERSION }} 
          docker push ${{ env.REGISTRY }}/$USER/$TAG:${{ env.VERSION }}
        |