name: dockerImage 
on:
  push: 
    branches: [ main ]
  pull_request: 
    branches: [ main ]
  jobs: 
    build:
      env: 
        TAG: mypackagesimage 
        PAT: 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
        USER: manucu2k
        REGISTRY: ghcr.io
        VERSION: latest
        DATABASE_URL: mongodb://localhost/test
        CI: true

      runs-on: ubuntu-latest 

      strategy:
        matrix:
          node: [ 16 ]
          mongodb: [ 5 ]

      steps:  
        - name: Checkout 
          uses: actions/checkout@v3
        
        - name: Node setup
          uses: actions/setup-node@v3
          with: 
            node-version: '16.14.2'
            cache: 'npm'  

        - name: Use MongoDB from Github actions
          uses: supercharge/mongodb-github-action@1.6.0  
          with: 
            mongodb-version: '5.0.14' 

        - name: Build Docker Image 
          run: docker build . -t $TAG 
        
        - name: Login to GHCR
          run: |
            echo $PAT | docker login ghcr.io -u $USER --password-stdin 
            docker tag $TAG ${{ env.REGISTRY }}/$USER/$TAG:${{ env.VERSION }} 
            docker push ${{ env.REGISTRY }}/$USER/$TAG:${{ env.VERSION }} 

        #- run: npm install
        #- run: npm test

