name: Build-Docker-Image 
on:
  push: 
    branches: [ main ]
  pull_request: 
    branches: [ main ]
  jobs: 
    runs-on: ubuntu-latest 
    env: 
      TAG: mypackagesimage 
      PAT: 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
      USER: manucu2k
      REGISTRY: ghcr.io
      VERSION: latest

    steps:
     
      - name: Login to GHCR
        run:  |
          echo $PAT | docker login ghcr.io -u $USER —password-stdin 
          docker tag $TAG ${{ env.REGISTRY }}/$USER/$TAG:${{ env.VERSION }} 
          docker push ${{ env.REGISTRY }}/$USER/$TAG:${{ env.VERSION }}
        |
        
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Build Docker Image 
        run: docker build . -t $TAG 
