name: Node.js CI

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: [ ubuntu-latest ] 

    strategy:
      matrix:
        node-version: [ 16 ]
        mongodb: [ 5 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.JS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Use MongoDB from Github actions
        uses: supercharge/mongodb-github-action@1.6.0  
        with: 
          mongodb-version: '5.0.14'

      - name: deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        #with:
          #server: ftp.samkirkland.com
          #username: myFtpUserName
          #password: ${{ secrets.ftp_password }}
          #target-server: example.com
          #remote-user: username
          #private-ssh-key: ${{ secrets.SSH_KEY }}
          #destination-path: ~/destinationFolder/


      

#- name: Login to GHCR
#  run: |
#    echo $PAT | docker login ghcr.io -u $USER --password-stdin 
#    docker tag $TAG ${{ env.REGISTRY }}/$USER/$TAG:${{ env.VERSION }} 
#    docker push ${{ env.REGISTRY }}/$USER/$TAG:${{ env.VERSION }} 