name: dockerImage 
on:
  push: 
    branches: [ main ]
  pull_request: 
    branches: [ main ]

  jobs: 
    build:
      runs-on: ubuntu-latest 
      strategy:
        matrix:
          node: [ 16 ]
      steps:  
        - name: Checkout 
          uses: actions/checkout@v3
          
        - uses: actions/setup-node@v3
            with: 
              node-version: '16.14.2'
          cache: 'npm'
        - name: Login to GHCR
          run:  |
            echo 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 | docker login ghcr.io -u manucu2k --password-stdin 
            docker tag mypackagesimage ghcr.io/manucu2k/mypackagesimage:latest 
            docker push ghcr.io/manucu2k/mypackagesimage:latest 
        
        - name: Build Docker Image 
          run: docker build . -t $TAG 
